services:
  - type: web
    name: combine-stats-tracker
    env: python
    buildCommand: cd frontend && npm install && npm run build && cd .. && pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    plan: free
    buildFilter:
      paths:
        - frontend/**
        - backend/**
        - requirements.txt
        - package.json
        - package-lock.json 