services:
  - type: web
    name: combine-stats-tracker-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    plan: free
    buildFilter:
      paths:
        - backend/**
        - requirements.txt

  - type: static
    name: woo-combine-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    buildFilter:
      paths:
        - frontend/**
        - package.json
        - package-lock.json 