services:
  - type: web
    name: combine-stats-tracker
    env: python
    buildCommand: cd frontend && npm install && npm run build && cd .. && pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    plan: free
    # Add Render rewrite rule for SPA routing
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    # Filter to trigger builds on frontend or backend changes
    buildFilter:
      paths:
        - frontend/**
        - backend/**
        - requirements.txt
        - package.json
        - package-lock.json 