"""Create initial tables

Revision ID: 3d0c54a1a1ee
Revises: 
Create Date: 2024-08-18 17:18:44.091160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Add SQLModel import if needed for types like AutoString


# revision identifiers, used by Alembic.
revision: str = '3d0c54a1a1ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age_group', sa.Enum('SIX_U', 'EIGHT_U', 'TEN_U', 'TWELVE_U', 'FOURTEEN_U', name='agegroupenum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('drillresult',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('drill_type', sa.Enum('FORTY_M_DASH', 'VERTICAL_JUMP', 'CATCHING', 'THROWING', 'AGILITY', name='drilltype'), nullable=False),
    sa.Column('raw_score', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drillresult')
    op.drop_table('player')
    # ### end Alembic commands ###
